require("plugins.plugins-setup")
-- require("plugins.githubtheme")
require("plugins.catppuccin")
require("plugins.alpha")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.indent-blankline")
require("plugins.comment2")
require("plugins.telescope")
require("core")
